# Generated by Django 3.0.6 on 2020-05-20 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostPost_Machine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boastorroast',
            name='title',
        ),
    ]
