# Generated by Django 3.0.6 on 2020-05-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostPost_Machine', '0002_remove_boastorroast_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastorroast',
            name='description',
            field=models.TextField(default='boast or roast something here'),
        ),
        migrations.AlterField(
            model_name='boastorroast',
            name='isBoast',
            field=models.BooleanField(default=False),
        ),
    ]
