# Generated by Django 3.0.6 on 2020-05-21 02:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ghostPost_Machine', '0003_auto_20200520_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastorroast',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='boastorroast',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
