# Generated by Django 3.0.6 on 2020-05-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostPost_Machine', '0004_auto_20200521_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastorroast',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boastorroast',
            name='vote_score',
            field=models.IntegerField(default=0),
        ),
    ]
