# Generated by Django 3.0.6 on 2020-05-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostPost_Machine', '0005_auto_20200521_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boastorroast',
            name='vote_score',
            field=models.IntegerField(),
        ),
    ]
